# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux8ja-YZgjMpOGMKKDHYG4N9dtWR0HTn
"""

x = [0.6, 1.9, 0.5, 0.2, -0.8, -1, -1.9, 0.5, 2, 0.5, 0, -0.1, -2]
y = [0, -0.5, -1.9, 1.5, -0.9, 1, 1.1, -1.5, 1.5, 1.8, -1, 1.6, -0.8]
c = [[ 3,  1, 10,  8,  6],
     [ 7, 10,  6,  0, 10],
     [ 1,  2,  4,  6,  4],
     [ 0,  5,  6, 11,  4],
     [ 0,  7,  6, 11,  6],
     [11,  8,  4,  6, 10],
     [ 9,  9,  0,  7,  7],
     [ 2,  0,  9,  5,  7],
     [ 2,  3,  1,  9,  6],
     [ 5,  3,  2, 10,  0]]
cord=[]
l=[]
for i in range(10):
  for j in range(5):
    cord.append([x[c[i][j]],y[c[i][j]]])
  l.append(cord)
  cord=[]

print(l)